id = "i3-sway-config"
name = "i3/Sway Config"
description = "Syntax highlighting for i3wm and swaywm configuration files."
version = "0.1.0"
schema_version = 1
authors = ["vh"]
repository = "https://github.com/vh-zed-exts/i3wm-syntax"

[grammars.i3config]
repository = "https://github.com/vh-zed-exts/i3wm-syntax"
commit = "a9c4a756d107ee25b2d359df434e73b085ecfade"
